# Analyze using Pandas

This workbook shows how to do data analysis using pandas set-based operations on the data.

In [1]:
import pandas as pd

fn = "datasets/lunch_10.csv"
dset = pd.read_csv( fn )

We can right away see an advantage of using pandas. Our dataset looks like a dataset
when we show it in ipython.

In [3]:
dset

,Date,School,Enrollment,Attendance,Hamburger,Pizza,HotDog,Skipped
0,2015-09-03,West Lincoln M.S.,435,427,160,41,73,153
1,2015-09-03,North Jefferson H.S.,452,406,149,144,7,106
2,2015-09-03,Outer Roosevelt M.S.,181,157,45,31,71,10
3,2015-09-03,West York High,292,241,83,88,3,67
4,2015-09-03,West King M.S.,189,168,47,56,20,45
5,2015-09-03,East York H.S.,459,457,26,34,279,118
6,2015-09-03,West Lincoln High,266,264,83,21,148,12
7,2015-09-03,West Jefferson M.S.,233,204,79,56,26,43
8,2015-09-03,North Lincoln M.S.,474,439,87,99,23,230
9,2015-09-03,Central Arthur H.S.,497,370,160,97,19,94
10,2015-09-04,West Lincoln M.S.,435,406,136,117,115,38
11,2015-09-04,North Jefferson H.S.,452,450,257,191,0,2
12,2015-09-04,Outer Roosevelt M.S.,181,134,51,32,15,36
13,2015-09-04,West York High,292,283,167,109,0,7
14,2015-09-04,West King M.S.,189,163,55,57,27,24
15,2015-09-04,East York H.S.,459,421,122,45,12,242
16,2015-09-04,West Lincoln High,266,225,1,15,89,120
17,2015-09-04,West Jefferson M.S.,233,191,1,2,54,134
18,2015-09-04,North Lincoln M.S.,474,398,128,74,89,107
19,2015-09-04,Central Arthur H.S.,497,437,197,194,26,20
20,2015-09-07,West Lincoln M.S.,435,348,204,39,7,98
21,2015-09-07,North Jefferson H.S.,452,411,138,12,176,85
22,2015-09-07,Outer Roosevelt M.S.,181,165,16,73,38,38
23,2015-09-07,West York High,292,285,133,52,47,53
24,2015-09-07,West King M.S.,189,188,52,74,8,54
25,2015-09-07,East York H.S.,459,408,149,21,121,117
26,2015-09-07,West Lincoln High,266,249,103,38,75,33
27,2015-09-07,West Jefferson M.S.,233,190,65,42,7,76
28,2015-09-07,North Lincoln M.S.,474,447,232,66,48,101
29,2015-09-07,Central Arthur H.S.,497,482,1,68,202,211
...,...,...,...,...,...,...,...,...
1770,2016-05-09,West Lincoln M.S.,435,374,211,149,3,11
1771,2016-05-09,North Jefferson H.S.,452,417,132,55,20,210
1772,2016-05-09,Outer Roosevelt M.S.,181,130,9,27,9,85
1773,2016-05-09,West York High,292,266,47,116,41,62
1774,2016-05-09,West King M.S.,189,162,86,14,26,36
1775,2016-05-09,East York H.S.,459,435,0,45,254,136
1776,2016-05-09,West Lincoln High,266,235,26,79,64,66
1777,2016-05-09,West Jefferson M.S.,233,187,30,10,46,101
1778,2016-05-09,North Lincoln M.S.,474,472,127,96,150,99
1779,2016-05-09,Central Arthur H.S.,497,426,174,105,45,102
1780,2016-05-10,West Lincoln M.S.,435,379,120,119,65,75
1781,2016-05-10,North Jefferson H.S.,452,388,96,167,102,23
1782,2016-05-10,Outer Roosevelt M.S.,181,170,79,34,3,54
1783,2016-05-10,West York High,292,274,135,69,16,54
1784,2016-05-10,West King M.S.,189,165,75,44,21,25
1785,2016-05-10,East York H.S.,459,407,166,26,138,77
1786,2016-05-10,West Lincoln High,266,226,87,4,0,135
1787,2016-05-10,West Jefferson M.S.,233,192,42,85,56,9
1788,2016-05-10,North Lincoln M.S.,474,462,171,19,1,271
1789,2016-05-10,Central Arthur H.S.,497,374,103,19,70,182
1790,2016-05-11,West Lincoln M.S.,435,394,20,175,35,164
1791,2016-05-11,North Jefferson H.S.,452,445,124,58,258,5
1792,2016-05-11,Outer Roosevelt M.S.,181,167,64,44,12,47
1793,2016-05-11,West York High,292,236,3,1,230,2
1794,2016-05-11,West King M.S.,189,180,18,76,14,72
1795,2016-05-11,East York H.S.,459,443,180,194,57,12
1796,2016-05-11,West Lincoln High,266,246,87,120,6,33
1797,2016-05-11,West Jefferson M.S.,233,183,25,48,39,71
1798,2016-05-11,North Lincoln M.S.,474,408,5,78,198,127
1799,2016-05-11,Central Arthur H.S.,497,448,46,181,165,56

Alright so how many unique schools and dates are in our dataset?

In [9]:
schools = dset.School.unique()
print( schools )
len( schools )

['West Lincoln M.S.' 'North Jefferson H.S.' 'Outer Roosevelt M.S.'
 'West York High' 'West King M.S.' 'East York H.S.' 'West Lincoln High'
 'West Jefferson M.S.' 'North Lincoln M.S.' 'Central Arthur H.S.']

10

In [10]:
len( dset.Date.unique() )

180

OK so now lets try and look at some statistics for the whole year. Lets take out the
date and just add up the data for each school into a whole year view.

In [17]:
wholeyear = dset.groupby( ["School" ]).agg( 'sum' )
wholeyear

,Enrollment,Attendance,Hamburger,Pizza,HotDog,Skipped
School,,,,,,
Central Arthur H.S.,89460,77843,24159,18207,19336,16141
East York H.S.,82620,77068,23331,18394,15755,19588
North Jefferson H.S.,81360,71455,21274,17172,16553,16456
North Lincoln M.S.,85320,75786,20900,17118,17597,20171
Outer Roosevelt M.S.,32580,27630,8070,6472,6248,6840
West Jefferson M.S.,41940,37175,10588,8732,9445,8410
West King M.S.,34020,29613,8393,7195,6574,7451
West Lincoln High,47880,43927,12906,10928,9490,10603
West Lincoln M.S.,78300,69819,20175,17043,16417,16184
West York High,52560,47523,14053,12097,10439,10934

Once we have this we can start figuring out things about the whole year, like
the average attendance at the school.

In [21]:
wholeyear.Attendance  / wholeyear.Enrollment * 100

School
Central Arthur H.S.     87.014308
East York H.S.          93.280077
North Jefferson H.S.    87.825713
North Lincoln M.S.      88.825598
Outer Roosevelt M.S.    84.806630
West Jefferson M.S.     88.638531
West King M.S.          87.045855
West Lincoln High       91.743943
West Lincoln M.S.       89.168582
West York High          90.416667
dtype: float64

We immediately see how much more powerful this is than the complicated loops we had to
do by thinking about this as rows. Similarly by aggreagating by days, we can answer a question like "on which day did we sell the most hamburgers school wide"

In [24]:
wholedistrict = dset.groupby( [ "Date" ] ).agg( "sum" )

In [28]:
wholedistrict.Hamburger.idxmax( )

'2015-12-29'

Or answer a question like "What's the average number of hot dogs, burgers, pizza, and skips per school in a year"

In [32]:
dset.drop( [ "Enrollment", "Attendance" ],axis=1).groupby( "School" ).agg( "mean" )

                       Hamburger       Pizza      HotDog     Skipped
School
Central Arthur H.S.   134.216667  101.150000  107.422222   89.672222
East York H.S.        129.616667  102.188889   87.527778  108.822222
North Jefferson H.S.  118.188889   95.400000   91.961111   91.422222
North Lincoln M.S.    116.111111   95.100000   97.761111  112.061111
Outer Roosevelt M.S.   44.833333   35.955556   34.711111   38.000000
West Jefferson M.S.    58.822222   48.511111   52.472222   46.722222
West King M.S.         46.627778   39.972222   36.522222   41.394444
West Lincoln High      71.700000   60.711111   52.722222   58.905556
West Lincoln M.S.     112.083333   94.683333   91.205556   89.911111
West York High         78.072222   67.205556   57.994444   60.744444